import { t, type Dictionary } from 'intlayer';
import { Edit } from 'lucide-react';
import type { ReactNode } from "react";

const pocContent = {
    key: 'poc-component',
    content: {
        title: t({
            en: 'Proof of Concept: Intlayer + OpenAI',
            pt: 'Prova de Conceito: Intlayer + OpenAI',
        }),
        description: t({
            en: 'This text is managed by Intlayer. In the future, the missing translations will be auto-generated by OpenAI!',
            pt: 'Este texto é gerenciado pelo Intlayer. No futuro, as traduções faltantes serão geradas automaticamente pela OpenAI!',
        }),
    },
} satisfies Dictionary;

export default pocContent;
