import { t, type Dictionary } from "intlayer";
import type { ReactNode } from "react";


const themeToggleContent = {
    key: "theme",
    content: {
        label: t({
            en: "Theme",
            pt: "Tema",
            fr: "Thème",
            es: "Tema",
            zh: "主题",
            ja: "テーマ",
            "en-GB": "Theme",
        }),
        themes: {
            light: t({
                en: "Light",
                pt: "Claro",
                fr: "Clair",
                es: "Claro",
                zh: "明亮",
                ja: "ライト",
                "en-GB": "Light",
            }),
            dark: t({
                en: "Dark",
                pt: "Escuro",
                fr: "Sombre",
                es: "Oscuro",
                zh: "暗黑",
                ja: "ダーク",
                "en-GB": "Dark",
            }),
            cupcake: t({
                en: "Cupcake",
                pt: "Cupcake",
                fr: "Cupcake",
                es: "Cupcake",
                zh: "杯形蛋糕",
                ja: "カップケーキ",
                "en-GB": "Cupcake",
            }),
            bumblebee: t({
                en: "Bumblebee",
                pt: "Abelha",
                fr: "Bourdon",
                es: "Abejorro",
                zh: "大黄蜂",
                ja: "バンブルビー",
                "en-GB": "Bumblebee",
            }),
            emerald: t({
                en: "Emerald",
                pt: "Esmeralda",
                fr: "Émeraude",
                es: "Esmeralda",
                zh: "祖母绿",
                ja: "エメラルド",
                "en-GB": "Emerald",
            }),
            corporate: t({
                en: "Corporate",
                pt: "Corporativo",
                fr: "Entreprise",
                es: "Corporativo",
                zh: "商务",
                ja: "コーポレート",
                "en-GB": "Corporate",
            }),
            synthwave: t({
                en: "Synthwave",
                pt: "Synthwave",
                fr: "Synthwave",
                es: "Synthwave",
                zh: "合成波",
                ja: "シンセウェーブ",
                "en-GB": "Synthwave",
            }),
            retro: t({
                en: "Retro",
                pt: "Retrô",
                fr: "Rétro",
                es: "Retro",
                zh: "复古",
                ja: "レトロ",
                "en-GB": "Retro",
            }),
            cyberpunk: t({
                en: "Cyberpunk",
                pt: "Cyberpunk",
                fr: "Cyberpunk",
                es: "Cyberpunk",
                zh: "赛博朋克",
                ja: "サイバーパンク",
                "en-GB": "Cyberpunk",
            }),
            valentine: t({
                en: "Valentine",
                pt: "Namorados",
                fr: "Valentin",
                es: "San Valentín",
                zh: "情人节",
                ja: "バレンタイン",
                "en-GB": "Valentine",
            }),
            halloween: t({
                en: "Halloween",
                pt: "Halloween",
                fr: "Halloween",
                es: "Halloween",
                zh: "万圣节",
                ja: "ハロウィン",
                "en-GB": "Halloween",
            }),
            garden: t({
                en: "Garden",
                pt: "Jardim",
                fr: "Jardin",
                es: "Jardín",
                zh: "花园",
                ja: "ガーデン",
                "en-GB": "Garden",
            }),
            forest: t({
                en: "Forest",
                pt: "Floresta",
                fr: "Forêt",
                es: "Bosque",
                zh: "森林",
                ja: "フォレスト",
                "en-GB": "Forest",
            }),
            aqua: t({
                en: "Aqua",
                pt: "Água",
                fr: "Aqua",
                es: "Agua",
                zh: "水色",
                ja: "アクア",
                "en-GB": "Aqua",
            }),
            lofi: t({
                en: "Lofi",
                pt: "Lofi",
                fr: "Lofi",
                es: "Lofi",
                zh: "低保真",
                ja: "ローファイ",
                "en-GB": "Lofi",
            }),
            pastel: t({
                en: "Pastel",
                pt: "Pastel",
                fr: "Pastel",
                es: "Pastel",
                zh: "粉彩",
                ja: "パステル",
                "en-GB": "Pastel",
            }),
            fantasy: t({
                en: "Fantasy",
                pt: "Fantasia",
                fr: "Fantaisie",
                es: "Fantasía",
                zh: "幻想",
                ja: "ファンタジー",
                "en-GB": "Fantasy",
            }),
            wireframe: t({
                en: "Wireframe",
                pt: "Aramado",
                fr: "Fil de fer",
                es: "Alambre",
                zh: "线框",
                ja: "ワイヤーフレーム",
                "en-GB": "Wireframe",
            }),
            black: t({
                en: "Black",
                pt: "Preto",
                fr: "Noir",
                es: "Negro",
                zh: "黑色",
                ja: "ブラック",
                "en-GB": "Black",
            }),
            luxury: t({
                en: "Luxury",
                pt: "Luxo",
                fr: "Luxe",
                es: "Lujo",
                zh: "奢华",
                ja: "ラグジュアリー",
                "en-GB": "Luxury",
            }),
            dracula: t({
                en: "Dracula",
                pt: "Dracula",
                fr: "Dracula",
                es: "Dracula",
                zh: "德古拉",
                ja: "ドラキュラ",
                "en-GB": "Dracula",
            }),
            cmyk: t({
                en: "CMYK",
                pt: "CMYK",
                fr: "CMJN",
                es: "CMYK",
                zh: "印刷色",
                ja: "CMYK",
                "en-GB": "CMYK",
            }),
            autumn: t({
                en: "Autumn",
                pt: "Outono",
                fr: "Automne",
                es: "Otoño",
                zh: "秋天",
                ja: "オータム",
                "en-GB": "Autumn",
            }),
            business: t({
                en: "Business",
                pt: "Negócios",
                fr: "Affaires",
                es: "Negocios",
                zh: "商务",
                ja: "ビジネス",
                "en-GB": "Business",
            }),
            acid: t({
                en: "Acid",
                pt: "Ácido",
                fr: "Acide",
                es: "Ácido",
                zh: "迷幻",
                ja: "アシッド",
                "en-GB": "Acid",
            }),
            lemonade: t({
                en: "Lemonade",
                pt: "Limonada",
                fr: "Limonade",
                es: "Limonada",
                zh: "柠檬水",
                ja: "レモネード",
                "en-GB": "Lemonade",
            }),
            night: t({
                en: "Night",
                pt: "Noite",
                fr: "Nuit",
                es: "Noche",
                zh: "夜晚",
                ja: "ナイト",
                "en-GB": "Night",
            }),
            coffee: t({
                en: "Coffee",
                pt: "Café",
                fr: "Café",
                es: "Café",
                zh: "咖啡",
                ja: "コーヒー",
                "en-GB": "Coffee",
            }),
            winter: t({
                en: "Winter",
                pt: "Inverno",
                fr: "Hiver",
                es: "Invierno",
                zh: "冬天",
                ja: "ウィンター",
                "en-GB": "Winter",
            }),
            dim: t({
                en: "Dim",
                pt: "Escurecido",
                fr: "Tamisé",
                es: "Tenue",
                zh: "暗淡",
                ja: "ディム",
                "en-GB": "Dim",
            }),
            nord: t({
                en: "Nord",
                pt: "Nórdico",
                fr: "Nord",
                es: "Nórdico",
                zh: "诺德",
                ja: "ノード",
                "en-GB": "Nord",
            }),
            sunset: t({
                en: "Sunset",
                pt: "Pôr do sol",
                fr: "Coucher de soleil",
                es: "Puesta de sol",
                zh: "日落",
                ja: "サンセット",
                "en-GB": "Sunset",
            }),
            caramellatte: t({
                en: "Caramel Latte",
                pt: "Caramelo Latte",
                fr: "Latte Caramel",
                es: "Latte Caramelo",
                zh: "焦糖拿铁",
                ja: "キャラメルラテ",
                "en-GB": "Caramel Latte",
            }),
            abyss: t({
                en: "Abyss",
                pt: "Abismo",
                fr: "Abysse",
                es: "Abismo",
                zh: "深渊",
                ja: "アビス",
                "en-GB": "Abyss",
            }),
            silk: t({
                en: "Silk",
                pt: "Seda",
                fr: "Soie",
                es: "Seda",
                zh: "丝绸",
                ja: "シルク",
                "en-GB": "Silk",
            }),
        }
    }
} satisfies Dictionary;

export default themeToggleContent;
